# Generated by Django 3.2.18 on 2023-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_xark3k', upload_to='samples/images/'),
        ),
    ]
